FROM golang:1.24-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o worker ./cmd/worker


FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/worker .

EXPOSE 7118

CMD ["./worker"]