x-service-templates:
  api: &api
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
      - redis
      - jaeger
    restart: always
    networks:
      - app
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '50M'
  worker: &worker
    build:
      context: .
      dockerfile: Dockerfile.worker
    depends_on:
      - postgres
      - redis
      - jaeger
    networks:
      - app
      - payment-processor
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '60M'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    networks:
      - app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '20M'

  api-1:
    <<: *api
    container_name: rinhaapi-1
    hostname: api1
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7118
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/rinha2025?pool_max_conns=5
      - TELEMETRY_ENABLED=true
      - TELEMETRY_SERVICE_NAME=rinha-service-1
      - JAEGER_URL=http://jaeger:14268/api/traces
      - SERVICE_DEFAULT_URL=http://payment-processor-default:8080/payments
      - SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - REDIS_URL=redis://redis:6379
      - REDIS_STREAM_NAME=payments
      - REDIS_STREAM_GROUP=payments-group
      - ENV=DEBUG

  api-2:
    <<: *api
    container_name: rinhaapi-2
    hostname: api2
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7118
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/rinha2025?pool_max_conns=5
      - TELEMETRY_ENABLED=true
      - TELEMETRY_SERVICE_NAME=rinha-service-2
      - JAEGER_URL=http://jaeger:14268/api/traces
      - SERVICE_DEFAULT_URL=http://payment-processor-default:8080/payments
      - SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - REDIS_URL=redis://redis:6379
      - REDIS_STREAM_NAME=payments
      - REDIS_STREAM_GROUP=payments-group

  worker-1:
    <<: *worker
    container_name: worker-1
    environment:
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=7118
      - POSTGRES_URL=postgres://postgres:password@postgres:5432/rinha2025?pool_max_conns=3
      - TELEMETRY_ENABLED=true
      - TELEMETRY_SERVICE_NAME=worker-1
      - JAEGER_URL=http://jaeger:14268/api/traces
      - SERVICE_DEFAULT_URL=http://payment-processor-default:8080/payments
      - SERVICE_FALLBACK_URL=http://payment-processor-fallback:8080/payments
      - REDIS_URL=redis://redis:6379
      - REDIS_STREAM_NAME=payments
      - REDIS_STREAM_GROUP=payments-group
      - REDIS_CONSUMER_NAME=worker-1


  redis:
    image: redis:8-alpine
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "63790:6379"
    networks:
      - app
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100M'
    restart: unless-stopped

  postgres:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=rinha2025
    ports:
      - "54320:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '100M'

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Collector HTTP endpoint
    networks:
      - app
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    restart: always


volumes:
  postgres_data:

networks:
  app:
    driver: bridge
  payment-processor:
    external: true
