server:
  port: 7118
  host: "localhost"

postgres:
  url: "postgres://postgres:password@localhost:5432/rinha2025"

redis:
  url: "redis://localhost:6379"
  stream_name: "payments"
  stream_group: "payments-group"
  consumer_name: "payment-worker-1"

telemetry:
  enabled: true
  service_name: "rinha-service"
  jaeger_url: "http://localhost:14268/api/traces"

service:
  default_url: "http://localhost:8001/payments"
  fallback_url: "http://localhost:8002/payments"
